"""Deterministic keyword/regex flags for free text. No model calls.

Flags earbud charging / bud-fault language in customer_message and agent_notes, with typo
tolerance (earbudds, dvice, jst, cahrging, ...). Used for (a) corroborating the lot alert and
(b) the validation set. Junk IVR rows are ignored. Everything here is rules only, cost Rs 0.

Two rule versions live here for an honest before/after (see validation/rule_v2_patterns.md):
  - v1 (`flag_text_v1`): the original rule. FROZEN — its behaviour must not change.
  - v2 (`flag_text_v2`): v1 OR the extra pattern groups mined from tickets OUTSIDE the 180
    sample and the 60 test set. Mining kept only the two groups with real positive bad-lot
    lift — dead / one-sided bud and wiggle/press-to-charge; it threw away no-green-light,
    won't-hold-charge and Hinglish (0 / negative lift — see comment below V2_GROUPS and
    validation/rule_v2_patterns.md). v2 fires wherever v1 fires, so recall(v2) >= recall(v1)
    by construction; the held-out 60-ticket test says whether the added recall costs precision.

`charging_fault_text` (the production column) stays bound to v1 so the money and lot outputs,
which never use it anyway, are provably unchanged.
"""
from __future__ import annotations

import re

import pandas as pd

# --- v1: original vocabulary (FROZEN — do not edit these five patterns or flag_text_v1) -------
_CHARGE = r"(?:charg|chrg|charing|cahrg|not taking charge|won'?t charge|no charge|dead|drain)"
_BUD = r"(?:bud|earbud|earbudd|ear bud|left|right|one side|one ear)"
_LED = r"(?:led|green light|no light|indicator|not lighting)"
_CASE = r"(?:case|lid|cradle|cover)"
_PAIR = r"(?:pair|pairing|bluetooth|connect|disconnect|keeps? cutting|drops? out)"

DEFECT_PATTERNS = {
    "charging": re.compile(_CHARGE),
    "bud_side": re.compile(_BUD),
    "led": re.compile(_LED),
    "case_lid": re.compile(_CASE),
    "pairing": re.compile(_PAIR),
}

# A ticket is charging/bud-fault positive when it mentions charging trouble AND a bud/side/led/case,
# or an explicit "left/right bud not charging"-style phrase.
_EXPLICIT = re.compile(
    r"(left|right|one)\s*(ear)?\s*bud(d)?s?.{0,25}" + _CHARGE + r"|"
    + _CHARGE + r".{0,25}(left|right|one)\s*(ear)?\s*bud(d)?s?"
)


def _text(message: str | float, notes: str | float) -> str:
    return " ".join(str(x) for x in (message, notes) if isinstance(x, str)).lower()


def flag_text_v1(message: str | float, notes: str | float) -> bool:
    """Rule-based charging/bud-fault flag for one ticket's free text. FROZEN v1 behaviour."""
    text = _text(message, notes)
    if not text.strip():
        return False
    if _EXPLICIT.search(text):
        return True
    has_charge = DEFECT_PATTERNS["charging"].search(text) is not None
    has_component = any(
        DEFECT_PATTERNS[k].search(text) for k in ("bud_side", "led", "case_lid")
    )
    return bool(has_charge and has_component)


# Backwards-compatible alias: the historical public name is v1.
flag_text = flag_text_v1


# --- v2: extra pattern groups (recall-oriented), mined outside the 180 sample ------------------
# Each group targets a Pulse-2 charging/power/dead-bud failure kind the v1 rule under-catches.
# The predictor is always "text rule AND SKU == VA-EB-PL2", so these do not need to name a
# product; the SKU gate keeps other products out. Corpus counts per group live in
# validation/rule_v2_patterns.md (generated by validation/mine_v2.py from the SAME regexes).
V2_GROUPS: dict[str, re.Pattern] = {
    # dead / one-sided bud, "just a decoration", "paperweight", stopped working
    "dead_or_one_sided": re.compile(
        r"(?:(?:one|left|right|1|single|only\s*one)\s*(?:ear\s*)?(?:bud|ear|side)"
        r".{0,30}(?:dead|not\s*work|stopped|no\s*sound|silent|decorat|useless|paper\s*weight|paperweight))"
        r"|(?:(?:bud|ear|earbud|piece|pod).{0,15}(?:just\s*)?(?:a\s*)?(?:decorat|useless|paperweight|paper\s*weight))"
        r"|(?:just\s*(?:a\s*)?decorat)"
    ),
    # have to wiggle / jiggle / press / hold it in the case to charge or work
    "wiggle_or_press": re.compile(
        r"(?:(?:wiggl|jiggl|wobbl|nudg|press|pressed|push|hold\s*it|holding\s*it|"
        r"move\s*it|adjust|re-?seat|reseat|fiddl).{0,30}"
        r"(?:charg|chrg|work|led|light|green|switch\s*on|turn\s*on))"
        r"|(?:(?:charg|chrg|work|led|green\s*light|switch\s*on|turn\s*on).{0,30}"
        r"(?:wiggl|jiggl|wobbl|nudg|press|push|hold\s*it|move\s*it|adjust|re-?seat|reseat|fiddl))"
    ),
}

# Groups the mining THREW AWAY (kept here as a comment so the decision is auditable):
#   - no_green_light / no-LED: 0 hits in the 811-ticket bad-lot corpus (the "never gets the
#     green light" phrasing lived in the 180 sample, which mining excludes); a broad form also
#     matched pairing chatter. A 0-support pattern earns no place.
#   - won't-hold-charge / battery-drain: negative lift (fires more on the healthy baseline —
#     battery-life questions — than on bad-lot tickets); it would cost precision for ~no recall.
#   - Hinglish charge-negation ("charge nahi", "kaam nahi"): 0 hits in the corpus; not added.
# Only groups with real, positive bad-lot lift ship in V2_GROUPS above.


def v2_group_hits(message: str | float, notes: str | float) -> dict[str, bool]:
    """Per-group v2 match (excludes the v1 contribution) — used by mine_v2.py for corpus counts."""
    text = _text(message, notes)
    if not text.strip():
        return {k: False for k in V2_GROUPS}
    return {k: (p.search(text) is not None) for k, p in V2_GROUPS.items()}


def flag_text_v2(message: str | float, notes: str | float) -> bool:
    """v2 = v1 OR any extra pattern group. Fires wherever v1 fires (recall >= v1)."""
    if flag_text_v1(message, notes):
        return True
    text = _text(message, notes)
    if not text.strip():
        return False
    return any(p.search(text) for p in V2_GROUPS.values())


def annotate(tickets: pd.DataFrame) -> pd.DataFrame:
    """Add `charging_fault_text` (=v1, production/frozen) plus `_v1`/`_v2` columns.

    Junk IVR rows are never flagged. Money and lot outputs do not read any of these columns,
    so switching versions here cannot move the rupee number."""
    t = tickets.copy()
    msg, notes = t["customer_message"], t["agent_notes"]
    v1 = pd.Series([flag_text_v1(m, n) for m, n in zip(msg, notes)], index=t.index)
    v2 = pd.Series([flag_text_v2(m, n) for m, n in zip(msg, notes)], index=t.index)
    not_junk = ~t["is_junk_ivr"]
    t["charging_fault_text_v1"] = v1 & not_junk
    t["charging_fault_text_v2"] = v2 & not_junk
    t["charging_fault_text"] = t["charging_fault_text_v1"]  # production stays on frozen v1
    return t
